"""add place details

Revision ID: 1056648ddcb7
Revises: 1c4b535d5ddc
Create Date: 2026-08-28 09:52:53.428662

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1056648ddcb7'
down_revision: Union[str, Sequence[str], None] = '1c4b535d5ddc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('place_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('place_id', sa.Integer(), nullable=False),
    sa.Column('entry_fee', sa.String(length=200), nullable=True),
    sa.Column('opening_hours', sa.String(length=300), nullable=True),
    sa.Column('best_time', sa.String(length=300), nullable=True),
    sa.Column('duration', sa.String(length=200), nullable=True),
    sa.Column('how_to_reach', sa.Text(), nullable=True),
    sa.Column('facilities', sa.Text(), nullable=True),
    sa.Column('ticket_url', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['place_id'], ['places.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('place_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('place_details')
    # ### end Alembic commands ###
