"""remove city from places

Revision ID: 17f5d2266f4d
Revises: bf5a666f52c2
Create Date: 2026-08-27 16:10:36.945823

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17f5d2266f4d'
down_revision: Union[str, Sequence[str], None] = 'bf5a666f52c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('places', 'name',
               existing_type=sa.VARCHAR(length=180),
               type_=sa.String(length=160),
               existing_nullable=False)
    op.alter_column('places', 'slug',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=180),
               existing_nullable=False)
    op.alter_column('places', 'short_description',
               existing_type=sa.TEXT(),
               type_=sa.String(length=300),
               existing_nullable=True)
    op.drop_index(op.f('ix_places_city_id'), table_name='places')
    op.drop_constraint(op.f('places_city_id_fkey'), 'places', type_='foreignkey')
    op.drop_column('places', 'city_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('places', sa.Column('city_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('places_city_id_fkey'), 'places', 'cities', ['city_id'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('ix_places_city_id'), 'places', ['city_id'], unique=False)
    op.alter_column('places', 'short_description',
               existing_type=sa.String(length=300),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('places', 'slug',
               existing_type=sa.String(length=180),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)
    op.alter_column('places', 'name',
               existing_type=sa.String(length=160),
               type_=sa.VARCHAR(length=180),
               existing_nullable=False)
    # ### end Alembic commands ###
