"""add place images

Revision ID: cf0700060a8a
Revises: 1056648ddcb7
Create Date: 2026-08-28 10:17:44.569011

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf0700060a8a'
down_revision: Union[str, Sequence[str], None] = '1056648ddcb7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('place_images', sa.Column('is_cover', sa.Boolean(), nullable=False))
    op.add_column('place_images', sa.Column('sort_order', sa.Integer(), nullable=False))
    op.alter_column('place_images', 'alt_text',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=300),
               existing_nullable=True)
    op.drop_column('place_images', 'display_order')
    op.drop_column('place_images', 'is_primary')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('place_images', sa.Column('is_primary', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('place_images', sa.Column('display_order', sa.INTEGER(), autoincrement=False, nullable=False))
    op.alter_column('place_images', 'alt_text',
               existing_type=sa.String(length=300),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
    op.drop_column('place_images', 'sort_order')
    op.drop_column('place_images', 'is_cover')
    # ### end Alembic commands ###
